config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: :logout

  resources :users
  resources :gifs

end

app/models/gif.rb
class Gif < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  belongs_to :user

  validates_presence_of :title, :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :gifs

  validates_presence_of :username, :name, :email
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to root_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  before_action :authorize

  def index
    @gifs = Gif.where('image IS NOT null').order('created_at DESC')
  end

  def new
    @gif = Gif.new
  end

  def create
    @gif = Gif.new(gif_params.except(:remote_image_url))
    @gif.user = current_user

    if @gif.save
      GifImageUploadWorker.perform_async(@gif.id, gif_params[:remote_image_url])
      flash[:success] = "You're image is being processed"
      redirect_to gifs_path
    else
      flash.now[:error] = @gif.errors.full_messages.to_sentence
      render :new
    end
  end

private

  def gif_params
    params.require(:gif).permit(:title, :remote_image_url, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    u = User.find_by(username: params[:user][:username])

    if u && u.authenticate(params[:user][:password])
      session[:user_id] = u.id
      redirect_to gifs_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:password, :password_confirmation, :username, :email, :name))

    if @user.save
      session[:user_id] = @user.id
      WelcomeEmailWorker.perform_async(@user.id)
      redirect_to gifs_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gifs/_gif_card.html.erb
<div class="card">
  <div class="card-image">
    <%= image_tag gif.image.url %>
  </div>
  <div class="card-copy">
    <%= gif.title %>
  </div>
</div>

app/views/gifs/index.html.erb
<%= link_to "postaGIF", new_gif_path %>

<div class='feed'>
  <h2>GIFs</h2>
  <div class="cards">
  <% @gifs.each do |gif| %>
    <%= render partial: 'gif_card', locals: { gif: gif } %>
  <% end %>
  </div>
</div>

app/views/gifs/new.html.erb
<%= form_for @gif do |f| %>
  <h4>Paste GIF url here</h4>
  <%= f.text_field :remote_image_url, placeholder: 'paste image url here' %>
  <h4>Title (make it flavorful ◕‿↼)</h4>
  <%= f.text_field :title, placeholder: 'title goes here' %>
  <%= f.submit 'POST' %>
<% end %>

app/views/home/index.html.erb
<h2>Welcome to Gifster!</h2>
<%= image_tag 'http://i.giphy.com/6459ZFRF1Wxna.gif', style: 'width: 100%;' %>
<span class='links'>
  <%= link_to "Signup", new_user_path, class: 'button' %> or <%= link_to "Login", login_path, class: 'button' %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gifster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class='brand'>Gifster</h1>

<% if current_user %>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Signup", new_user_path %> or <%= link_to "Login", login_path %>
<% end %>

<div class='container'>
  <% flash.each do |key,msg| %>
    <div class="flash-<%= key %>">
      <span><%= msg %></span>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/users/new.html.erb
<h2>Signup!</h2>

<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: 'Your name' %>
  <%= f.text_field :email, placeholder: 'Your email' %>
  <%= f.text_field :username, placeholder: 'Username' %>
  <%= f.password_field :password, placeholder: 'Password' %>
  <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
  <%= f.submit "Join Gifster" %>
<% end %>